version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-milk-hiring
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_db_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_db_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-milk-hiring
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: mongo_db_user
      MONGO_PASSWORD: mongo_db_password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

volumes:
  mongodb_data:
